/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';

import { useGLTF } from '@react-three/drei';
import * as THREE from 'three';
// eslint-disable-next-line import/no-extraneous-dependencies
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    roundTables: THREE.Mesh;
    heaters: THREE.Mesh;
    sinks: THREE.Mesh;
    roof_items: THREE.Mesh;
    kitchenShelf: THREE.Mesh;
    microwaves: THREE.Mesh;
    waterDispencer: THREE.Mesh;
    toaster: THREE.Mesh;
    coffeeExpress: THREE.Mesh;
    grinder: THREE.Mesh;
    coffeeAccesories: THREE.Mesh;
    windows: THREE.Mesh;
    doors: THREE.Mesh;
    woodenElements: THREE.Mesh;
    fridge: THREE.Mesh;
    floorAndRoof: THREE.Mesh;
    wallsAndBricks: THREE.Mesh;
    lights: THREE.Mesh;
    chairs: THREE.Mesh;
    sofa: THREE.Mesh;
  };
  materials: {
    elementsMaterial: THREE.MeshStandardMaterial;
  };
};

export function Kitchen({
  ...props
}: JSX.IntrinsicElements['group']): JSX.Element {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(
    '/kitchen.gltf'
  ) as unknown as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.roundTables.geometry}
        material={nodes.roundTables.material}
        position={[-0.59, 0.67, 0.02]}
        rotation={[0, -1.54, 0]}
      />
      <mesh
        geometry={nodes.heaters.geometry}
        material={nodes.heaters.material}
        position={[-2.81, 0.27, 0.89]}
      />
      <mesh
        geometry={nodes.sinks.geometry}
        material={nodes.sinks.material}
        position={[0.32, 1.12, -5.61]}
      />
      <mesh
        geometry={nodes.roof_items.geometry}
        material={nodes.roof_items.material}
        position={[2.56, 2.73, -2.27]}
      />
      <mesh
        geometry={nodes.kitchenShelf.geometry}
        material={nodes.kitchenShelf.material}
        position={[3.08, 1.48, -4.16]}
      />
      <mesh
        geometry={nodes.microwaves.geometry}
        material={nodes.microwaves.material}
        position={[0.32, 1.12, -5.61]}
      />
      <mesh
        geometry={nodes.waterDispencer.geometry}
        material={nodes.waterDispencer.material}
        position={[0.32, 1.12, -5.61]}
      />
      <mesh
        geometry={nodes.toaster.geometry}
        material={nodes.toaster.material}
        position={[0.32, 1.12, -5.61]}
      />
      <mesh
        geometry={nodes.coffeeExpress.geometry}
        material={nodes.coffeeExpress.material}
        position={[0.32, 1.12, -5.61]}
      />
      <mesh
        geometry={nodes.grinder.geometry}
        material={nodes.grinder.material}
        position={[0.32, 1.12, -5.61]}
      />
      <mesh
        geometry={nodes.coffeeAccesories.geometry}
        material={nodes.coffeeAccesories.material}
        position={[0.32, 1.12, -5.61]}
      />
      <mesh
        geometry={nodes.windows.geometry}
        material={nodes.windows.material}
        position={[-2.81, 0.27, 0.89]}
      />
      <mesh
        geometry={nodes.doors.geometry}
        material={nodes.doors.material}
        position={[2.56, 2.73, -2.27]}
      />
      <mesh
        geometry={nodes.woodenElements.geometry}
        material={nodes.woodenElements.material}
        position={[-0.59, 0.67, 0.02]}
        rotation={[0, -1.54, 0]}
      />
      <mesh
        geometry={nodes.fridge.geometry}
        material={nodes.fridge.material}
        position={[3.08, 1.48, -4.16]}
      />
      <mesh
        geometry={nodes.floorAndRoof.geometry}
        material={nodes.floorAndRoof.material}
        position={[0, -0.18, 0]}
      />
      <mesh
        geometry={nodes.wallsAndBricks.geometry}
        material={nodes.wallsAndBricks.material}
      />
      <mesh
        geometry={nodes.lights.geometry}
        material={nodes.lights.material}
        position={[-1.28, 2.37, 3.13]}
      />
      <mesh
        geometry={nodes.chairs.geometry}
        material={nodes.chairs.material}
        position={[-1.52, 0.63, 2.63]}
        rotation={[1.15, -1.12, 1.11]}
      />
      <mesh
        geometry={nodes.sofa.geometry}
        material={nodes.sofa.material}
        position={[-2.25, 0.61, 5.45]}
      />
    </group>
  );
}

useGLTF.preload('/kitchen.gltf');
