/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';

import { useGLTF } from '@react-three/drei';
import * as THREE from 'three';
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader';

type GLTFResult = GLTF & {
  nodes: {
    floor: THREE.Mesh;
    nonTexturesWall: THREE.Mesh;
    wall_windows: THREE.Mesh;
    kitchen: THREE.Mesh;
    counter_cutter001: THREE.Mesh;
    Cube040: THREE.Mesh;
    kitchen_utensils: THREE.Mesh;
    roof_items: THREE.Mesh;
    roof_items001: THREE.Mesh;
    hanginLights: THREE.Mesh;
    chairs: THREE.Mesh;
    tables: THREE.Mesh;
    Cube014: THREE.Mesh;
    wallsWithBricks: THREE.Mesh;
    windowsAndHeaters: THREE.Mesh;
    south_wall: THREE.Mesh;
  };
  materials: {
    floorAndRoofMaterial: THREE.MeshStandardMaterial;
    darkWallMaterial: THREE.MeshStandardMaterial;
    wallWindows: THREE.MeshStandardMaterial;
    kitchenMaterial: THREE.MeshStandardMaterial;
    woodenPanelsWestMaterial: THREE.MeshStandardMaterial;
    windowPanelsMaterial: THREE.MeshStandardMaterial;
    utensilsMaterial: THREE.MeshStandardMaterial;
    pipesAndDoorsMaterial: THREE.MeshStandardMaterial;
    birchWoodMaterial: THREE.MeshStandardMaterial;
    lightsMaterial: THREE.MeshStandardMaterial;
    chairsMaterial: THREE.MeshStandardMaterial;
    tablesMaterial: THREE.MeshStandardMaterial;
    sofaMaterial: THREE.MeshStandardMaterial;
    bricksAndBarsMaterial: THREE.MeshStandardMaterial;
    windowsAndHeatersMaterial: THREE.MeshStandardMaterial;
    whiteWallMaterial: THREE.MeshStandardMaterial;
  };
};

export function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(
    '/kitchen.gltf'
  ) as unknown as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-1.28, 2.24, -2.64]}>
        <spotLight
          intensity={100}
          angle={0.88}
          penumbra={0.15}
          decay={2}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[0.97, 2.24, -2.64]}>
        <spotLight
          intensity={100}
          angle={0.88}
          penumbra={0.15}
          decay={2}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[-1.28, 2.24, -0.96]}>
        <spotLight
          intensity={100}
          angle={0.88}
          penumbra={0.15}
          decay={2}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[0.97, 2.24, -0.96]}>
        <spotLight
          intensity={100}
          angle={0.88}
          penumbra={0.15}
          decay={2}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[-1.28, 2.24, 1.56]}>
        <spotLight
          intensity={100}
          angle={0.88}
          penumbra={0.15}
          decay={2}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[0.97, 2.24, 1.56]}>
        <spotLight
          intensity={100}
          angle={0.88}
          penumbra={0.15}
          decay={2}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[-1.28, 2.24, 3.13]}>
        <spotLight
          intensity={100}
          angle={0.88}
          penumbra={0.15}
          decay={2}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[0.97, 2.24, 3.13]}>
        <spotLight
          intensity={100}
          angle={0.88}
          penumbra={0.15}
          decay={2}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[1.09, 2.76, 2.36]}>
        <pointLight
          intensity={29.6}
          decay={2}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[-1.24, 2.76, 2.36]}>
        <pointLight
          intensity={29.6}
          decay={2}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <mesh
        geometry={nodes.floor.geometry}
        material={materials.floorAndRoofMaterial}
        position={[0, -0.18, 0]}
      />
      <mesh
        geometry={nodes.nonTexturesWall.geometry}
        material={materials.darkWallMaterial}
      />
      <mesh
        geometry={nodes.wall_windows.geometry}
        material={materials.wallWindows}
        position={[-2.38, 2.05, -5.83]}
      />
      <mesh
        geometry={nodes.kitchen.geometry}
        material={materials.kitchenMaterial}
        position={[3.08, 1.48, -4.16]}
      />
      <mesh
        geometry={nodes.counter_cutter001.geometry}
        material={materials.woodenPanelsWestMaterial}
        position={[2.67, 1.41, 4.6]}
      />
      <mesh
        geometry={nodes.Cube040.geometry}
        material={materials.windowPanelsMaterial}
        position={[-2.69, 0.97, 4.27]}
      />
      <mesh
        geometry={nodes.kitchen_utensils.geometry}
        material={materials.utensilsMaterial}
        position={[0.32, 1.12, -5.61]}
      />
      <mesh
        geometry={nodes.roof_items.geometry}
        material={materials.pipesAndDoorsMaterial}
        position={[2.56, 2.73, -2.27]}
      />
      <mesh
        geometry={nodes.roof_items001.geometry}
        material={materials.birchWoodMaterial}
        position={[2.56, 2.73, -2.27]}
      />
      <mesh
        geometry={nodes.hanginLights.geometry}
        material={materials.lightsMaterial}
        position={[-0.85, 2.89, -3.57]}
      />
      <mesh
        geometry={nodes.chairs.geometry}
        material={materials.chairsMaterial}
        position={[-2.28, 0.45, 1.74]}
        rotation={[1.75, 1.15, -1.77]}
        scale={[0.12, 0.12, 0.12]}
      />
      <mesh
        geometry={nodes.tables.geometry}
        material={materials.tablesMaterial}
        position={[-1.03, 0.37, 4.64]}
      />
      <mesh
        geometry={nodes.Cube014.geometry}
        material={materials.sofaMaterial}
        position={[2.45, 0.65, 0.16]}
        scale={0.88}
      />
      <mesh
        geometry={nodes.wallsWithBricks.geometry}
        material={materials.bricksAndBarsMaterial}
        position={[-2.62, 1.64, -5.74]}
      />
      <mesh
        geometry={nodes.windowsAndHeaters.geometry}
        material={materials.windowsAndHeatersMaterial}
        position={[-2.81, 0.27, 0.89]}
      />
      <mesh
        geometry={nodes.south_wall.geometry}
        material={materials.whiteWallMaterial}
      />
    </group>
  );
}

useGLTF.preload('/kitchen.gltf');
